       ORG 00H
       LJMP MAIN

       

MAIN:	MOV R0,#05H 		; RUNNING TIMER LOOP FOR 7 TIME
    	MOV TMOD,#01H  		; TIMER IN MODE 1	
		MOV P1,#00H			; CLEARING PORT 0 FOR OUTPUT
		MOV TL0,#255        ; LOADING VALUE 255 and 200 IN TLO AND THO FOR 300MS DELAY
		MOV TH0,#200        ; 
		SETB TR0         ; START TIMER
		
		; MORSE CODE CONTAILS . AND - TO REPRESENT CHARACTERS. 
		; . MEANS SINGLE UNIT TIME AND DASH EQUALS 3 DASH.
		; EACH ELEMENT IS SEPARATED BY ONE BLANK UNIT TIME
		; EACH CHARACTER IS SEPARATED BY 3 BLANK UNIT TIME
		
AGAIN:  MOV R1,#4
HERE:	DJNZ R1,NEXT 
NEXT:   SETB P1.0				; H   IS EXPRESSED AS (....) IN MORSE CODE
	ACALL DELAY
	CLR P1.0
	ACALL DELAY
 	MOV A,R1
	JNZ HERE
	
	ACALL DELAY
	ACALL DELAY
	SETB P1.0
	ACALL DELAY               ; E (.)
	CLR P1.0
	ACALL DELAY_3
	
	SETB P1.0
	ACALL DELAY_3
	CLR P1.0
	ACALL DELAY				; y(-.-)
	SETB P1.0
	ACALL DELAY_3
	CLR P1.0
	ACALL DELAY
	SETB P1.0
	ACALL DELAY_3
	CLR P1.0
	ACALL DELAY

	LJMP AGAIN
	






        		
DELAY:	DJNZ R0,CHECK       ; RUN THIS DELAY LOOP RO TIMES
CHECK:	JNB TF0,CHECK     
		CLR TF0
		MOV A,R0
		JNZ DELAY        			
		MOV R0,#05H      ; RELOADING LOOP VALUE 
		MOV TL0,#255 ; RELOADING TLO,TH0 REGISTERS
		MOV TH0,#200      ;
		MOV IE,#00H       ; DISABLING INTERRUPT
		RET
			

			
 
DELAY_3: MOV R2,#4
DE:		 DJNZ R2,DELAY_1		; DELAY OF 3 UNIT TIME TO REPRESENT '-' IN MORSE CODE
		 RET
DELAY_1: ACALL DELAY
		 SJMP DE
