       ORG 00H
       LJMP MAIN

       

MAIN:	MOV A,#07H 		; RUNNING TIMER LOOP FOR 7 TIME
    	MOV TMOD,#01H  		; TIMER IN MODE 1	
		MOV P1,#00H			; CLEARING PORT 0 FOR OUTPUT
		MOV TL0,#00  ; LOADING VALUE 99FFh IN TLO AND THO FOR 455MS DELAY
		MOV TH0,#99H        ; 
		SETB TR0         ; START TIMER
		
AGAIN:  MOV R1,#4
HERE:	DJNZ R1,NEXT 
NEXT:   SETB P1.0
		ACALL DELAY_1
		CLR P1.1
		ACALL DELAY_1
		JNZ HERE
		
        		
DELAY_1:	DJNZ A,CHECK       ; RUN THIS DELAY LOOP RO TIMES
CHECK:	JNB TF0,CHECK     
		CLR TF0
		JNZ DELAY_1	        			
		MOV A,#07H      ; RELOADING LOOP VALUE 
		MOV TL0,#00 ; RELOADING TLO,TH0 REGISTERS
		MOV TH0,#99H      ;
		MOV IE,#00H       ; DISABLING INTERRUPT
		RET
			

			
